Storage Backend initial implementation
alefmanvladimir/BigFiles pull request #7
Opened 2023-10-11 20:29 UTC by DenisKusakin

Initial backend implementation, this is quite simple but it works
What included:
1. Endpoint for file upload
2. Endpoint for contract creation
3. Blueprint script to test the flow: `create sample file => upload => create contract`

Backend relies on **storage-daemon**, also I have a VM with **storage-daemon** and **ton-drive-backend** running so you can use them if needed(of course this is not super reliable, if there is a better place to deploy those services - I can do it)
VM IP: 159.223.4.194
Ton Drive Backend: http://159.223.4.194:3000

2023-10-12 05:33 UTC, d0rich requested changes
Overall, it looks cool

Left some comments to improve readability.

And there are some additional comments:

1. It would be nice to mention somewhere, that there is a prerequisite in face of downloaded `storage-daemon-cli` binaries (I think, we can create npm script to automate in future).
2. I see, you deployed backend on some VM. Which provider do you use, if it's not a secret? As I know, @alefmanvladimir have credentials to some cluster. Ask him about this. Maybe it is possible to automate deploy via GitHub actions.
3. At the moment, it is more reliable to test it without any storage provider. Anyway, your functionality for creating smart contracts looks useful for the future.

2023-10-12 05:33 UTC, d0rich commented on ton-drive-backend/src/ton-storage.service.ts
Did you check [`tonstorage-cli`](https://github.com/ndatg/tonstorage-cli/tree/main)?

Looks like it can help write more understandable code, using CLI wrapper.

2023-10-12 05:33 UTC, d0rich commented on ton-drive-backend/src/ton-storage.service.ts
> +// USE_SHELL=false
Please create `.env.example` file with these parameters.

2023-10-12 05:33 UTC, d0rich commented on ton-drive-contracts/scripts/testStorage.ts
> +  const bagId = await fetch("http://159.223.4.194:3000/upload", {
I think it is better to keep IP address and port as environment variables, because there is no guarantee that this VM will exist forever.

2023-10-12 05:33 UTC, d0rich commented on ton-drive-backend/src/ton-storage.controller.spec.ts
There is no ton-storage controller, so you can't create tests for it. I think you should rename this file into `ton-storage.service.spec.ts`

2023-10-12 05:33 UTC, d0rich commented on ton-drive-backend/src/ton-storage.service.ts
> +}
Why not make `parseCreateCmdOutput()` part of the service class? If you want to hide it in the instance and keep it testable, you can:

1. make method static
2. use [symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) and create private method for usage convenience inside class instance

2023-10-14 12:20 UTC, DenisKusakin commented on ton-drive-backend/src/ton-storage.service.ts
Added prerequisites to README, I don't thinks it makes sense to automate it with npm, from my understanding this should be automated in other way on infra level(nodejs and npm installation could be automated as well). I suggest to automate it later

Right now the service is deployed in my personal Digital Ocean VM, I'll deploy it to the ton-provider as soon as we have access

As we discussed, storage-provider could be useful because otherwise it won't be possible to link assets to owner. For testing you can just upload, no need to create storage contract, files would be available for download from outside anyway

**tonstorage-cli** looks good but there are some issue:
- for some reason it does not work locally(probably it is on my end)
- the library hardcodes `--json` flag, there is no way to override it. The problem with this flag is that the output differs from one when flag is not specified, in particular `--json` will print file hash instead of `bagId`(we need bagId). I believe that `bagId` could be somehow evaluated from hash but I don't know how. I couldn't find a way to get `bagId` using `--json`

2023-10-15 06:45 UTC, d0rich approved these changes

2023-10-15 06:45 UTC, d0rich commented on ton-drive-backend/src/ton-storage.service.ts
Okay, thank you. I believe we can deal with it later.

2023-10-15 06:54 UTC, merged

2023-11-03 15:34 UTC, ton-islaw commented
Hi, I'm about pizza from ton))) Please write your telegram

2023-11-03 16:05 UTC, DenisKusakin commented
> Hi, I'm about pizza from ton))) Please write your telegram

@denis_k_12